### ISSUE TITLE
How to build the project

### ISSUE THREAD

**Issue by Sumail2020** [JiaweiZhang-THU/CAVSim#2]
您好，您团队的工作很棒。我想请教一下安装此项目的问题：
1. 我应该在windows还是linux下部署这个项目呢？  您的代码看上去是在windows下编写的，但是pthread库文件需要自己配置。
2. 我无法在visual studio下运行您的代码（缺少工程文件），同时在windows环境g++编译时出现了一些问题。
![捕获2](https://github.com/JiaweiZhang-THU/CAVSim/assets/71431119/8f6a4aa7-2405-46a9-9153-cb914985fc5a)

**Comment by lxjlu** [comment]
同问，在windows下编译好多问题，应该不是g++编译的，希望能出个编译说明。
